apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-route
  namespace: conservecloud
spec:
  parentRefs:
    - name: tp-gateway
  hostnames:
    - "api-cath.10.108.143.255.nip.io"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: backend
          port: 80